evancohen/smart-mirror

css/main.css
Use a constant 4 spaces in [`main.css`](https://github.com/evancohen/smart-mirror/blob/master/css/main.css) as opposed to a random mix of tabs, 4 spaces and 2 spaces.
=> Make CSS spacing uniform

js/controller.js
Just because Annyang often interprets "name is" as "name's"
=> Allow "My name's *name"

js/controller.js
Change `allSpeach` to `allSpeech`
=> Fix a small typo

js/weather-service.js
no more problem with CORS getting the forecast using jsonp & callback=json
=> bypassing CORS using jsonp

README.md
I believe this was extra text that accidentally stayed instead of being removed in one of the newer commits.
=> Remove left-over text for Python

js/weather-service.js
=> Use automatic weather units

js/controller.js
Show map will now center at current location instead of Seattle, WA.
=> Show map center at current location

index.html, js/controller.js, js/hue-service.js
light groups are changed to 0's...
added color loop, stop
colors are all set via xy coordinators now
lights can be set to say 25% bightness by saying "Turn lights to 25%"
=> hue-service.js update

config.js, css/main.css, js/calendar-service.js
#60 Allow user to specify number of days and results to display for calendar.
#94  Added more spacing to calendar day column.
=> Allow user to specify number of days and results to display for calendar

config.js, css/main.css, index.html, js/controller.js, js/traffic-service.js
Extending @kurtdb's work on traffic.
=> Traffic modifications

css/main.css, index.html, js/config.js, js/controller.js, js/soundcloud-service.js
Meh, I really wanted the widget to work :<
=> SoundCloud integration

bower.json, config.example.js, index.html, js/app.js, js/controller.js, js/weather-service.js, main.js, package.json
Cleaning up a few things :rocket:
=> Fixing localization and cleaning up controller

js/calendar-service.js
Fixes the issue with google calendar events with alarms/notifications. 
Fixes #130
=> Fixes google calendar events with alarms issue

locales/ko-KR.js, locales/ko.js
Hello.
I add "locales/ko.js" file.
=> Add locales KO

css/main.css, index.html, js/controller.js, js/timer-service.js, main.js, sass/main.scss
I created a basic timer service.
You can start the timer by a spoken duration (e.g.: "2 minutes and 30 seconds"), stop and resume it. I also added a command to show the timer in case the focus of the scope changed. The circle stroke is animated using a CSS animation for improved performance.
Four new voice commands:
- `(set a) timer (for) *duration`
- `stop (the) timer`
- `resume (the) timer`
- `show (the) timer`
This code is not ready for production yet but it works quite well. However, this is my first angular project and I'm not even sure if I did everything correctly so I decided to open this pull request to get some feedback and maybe some help.
Some things to be improved: 
- Show the timer in a minimized view in case the scope changes and timer is running
- Play a sound and/or give …
=> Timer service

js/controller.js
I added "stop video" command for "search" branch.
=> add "stop video" command

js/timer-service.js, locales/de.json, locales/en.json, locales/es.json, locales/fr.json, locales/ko.json
I fully localized the timer service, commands are inspired by Apples voice assistant "Siri" and should be straightforward. Korean translations are still missing, the other ones (except german) should be checked for mistakes.
#182
=> Translations for timer service

js/timer-service.js, locales/de.json, locales/en.json, locales/es.json, locales/fr.json, locales/ko.json
I added Korean translations for the timer service.
=> Korean translations for a timer service

js/controller.js, locales/de.json, locales/en.json, locales/es.json, locales/fr.json, locales/ko.json, main.js
=> Removing "Hi my name is" and removing the crash reporter

install.sh, scripts/install.sh
Removed wget and home brew. Also moved install.sh to script folder
=> Shell Script install.sh

scripts/install.sh
Added sed command to rotate canvas and hide mouse configs
=> Added sed command to rotate canvas and hide mouse configs

config.example.js, index.html, js/timebox-service.js, js/traffic-service.js
Currently the traffic information is shown 24 hours a day. Chances are that people don't need the information the whole time, so I added the possibility to timebox the information. If the start time is not set or the current time is between the start time and end time, the traffic information is shown. In the other situation, the information is not fetched.
=> Add possibility of timeboxing the traffic information

js/controller.js
I had a situation in which the length of my greetings for night were less than that of the morning. So the array index was out of bounds, and the greeting was undefined. I fixed it below by getting the length of config.greeting[greetingTime] instead. 
Thanks,
-Sanjeev
=> Small Tweak in GreetingUpdater

config.example.js, js/hue-service.js, locales/de.json, locales/en.json, locales/es.json, locales/fr.json, locales/ko.json
Translation for Hue Service. Allow to change colors of a specific light, or update all lights by default
=> Add Hue service translation

css/main.css, index.html, js/controller.js, js/reminder-service.js, locales/de.json, locales/en.json, locales/es.json, locales/fr.json, locales/ko.json
Include reminder-service which can add, consult or delete list of reminders.
=> Reminder service

locales/de.json
Adapt german translations to match the meaning and the german grammar.
=> Change german translations

config.example.js, css/icesnow.css, js/geolocation-service.js, js/weather-service.js, sass/icesnow.scss
Hello,
simple but important for bugs with browser location detection.
=> make possible to set the location

index.html, js/controller.js, js/services/soundcloud.js
1. I changed the stroke color of the visualizer.
2. I removed the "getUserMedia()" method. Instead of using the "getUserMedia()" method, we can analyze audio sound and visualize it by using the "audio" tag.
=> change soundcloud.js

js/controller.js
I forget the "s" from the word "SoundCloudService". So I fixed it.
=> I forget the "s" from the word "SoundCloudService".

js/services/calendar.js
Fixed the issue with the recurring events that went wrong.
=> Fix for #172.

config.example.js, main.js, motion/motiondetect.py, pir-hdmi/pir-hdmi.py
Based on dev branch... Added python code to detect Motion on pin 26 on
raspberry pi. Spawns process in main.js... pulls vars from config.js
file.
in response to #286
really hated the name PIR-HDMI and changed to motion along with my branch name.
still having issues similar to what @missionrulz had on PR #128 where HDMI doesn't fully wake up...
=> Motion detect

config.example.js, js/controller.js
Add option for number of minutes the information is refreshed.
Forecast.io limits requests to 1000/day: a 2min interval = 720 calls/day
=> [FEATURE] Reload weather every two minutes.

config.example.js, js/controller.js, js/services/autosleep.js, js/services/geolocation.js, js/services/light.js
=> [CLEANUP] Config keys should be camelCased

config.example.js, css/main.css, index.html, js/controller.js, js/services/stock.js
One of the missing core features: people can now show their stock information on the screen.
Possible improvement on this, is to limit the number of items on screen.
=> Add the stock-ticker information on screen.

scripts/bash-start.sh
Usage: 
Add the following line to the end of **`/home/pi/.config/lxsession/LXDE-pi/autostart`**
``` bash
/home/pi/smart-mirror/scripts/bash-start.sh &
```
=> checking in bash boot script fixes #109

index.html, js/controller.js, locales/de.json, locales/en.json, locales/es.json, locales/fr.json, locales/ko.json
- Added localization for de and en
- Other supported languages fallback to en
- Made use of ng-show to display fitbit data only when there is data available
- Added fitbit command to the commands array and removed it from the index.html
This PR references #340.
=> Localization and UI Logic for Fitbit

config.example.js, locales/de.json, locales/en.json, locales/es.json, locales/fr.json, locales/ko.json
- Added full stops to all descriptions
- Localized non-german descriptions in de.json
- Changed wording of a few commands
This PR references #342.
=> Made locales consistent

js/controller.js, js/services/rss.js
@kurtdb did you want to make any other changes here, or are we safe to merge this in?
=> Fixed the discontinued google feed api as defined in #332.

css/main.css, index.html, js/controller.js, js/services/calendar.js
=> [CALENDAR] Polish day/multi-day formatting.

index.html, js/controller.js, js/services/stock.js
I updated the source of the information to be the yahoo yql service, since the yahoo finance information is actually an unsupported platform.
I also added the price change percentage, as requested by @justbill2020.
=> Updated the stock information to the yahoo yql service.

js/controller.js
=> Fixed issue with an individual stock quote not rendering.

config.example.js
=> Updated giphy api key

css/main.css, index.html, js/services/soundcloud.js, package.json
- Giphy Beta API key included in example config
- Removed some unesesary dependencies
- Fix a bug in SoundCloud search
=> 0.0.4 Minor update

.gitignore, config.example.js, css/main.css, index.html, js/controller.js, js/services/speech.js, main.js, package.json, sonus.js
I've been off the radar for a while on this project, but it's not like I haven't been doing work... With the power of [Sonus](https://github.com/evancohen/sonus), I will solve all complex smart mirror configuration woes in one fell swoop!
**This change...**
- Removes python as a dependency
- No longer uses webkitSpeechRecognition
- Lets you use unlimited requests ([within reason](https://cloud.google.com/speech/pricing#pricing_table))
- Doesn't require crazy microphone configuration
- Doesn't require the difficult process of obtaining chromium speech keys
🚀
=> Using Sonus for keyword spotting and streaming recognition

index.html, js/services/speech.js, package.json
Adding annyang as a npm dependency and monky patching it onto Sonus (which admittedly has Annyang baked in, but we can't use it in this situation).
=> update annyang. closes #392

scripts/conf-audio.sh
very rough draft of a script to configure .asoundrc very easily
=> audio config script

sonus.js
tested this... it works if there's just a string value for a single file or if you add an array for the model value with a list of files...
this can be merged to the dev branch and is ready for the next pull to master... i'm closing #442
=> add capability to use multiple hotwords for activation. fixes #442

.gitignore, index.html
Thinking that this should be included with v0.0.6 so I'm going to merge it to dev before the upgrade. It's a small enough change that I don't think that it introduces much risk.
=> add basic client side error logging

js/controller.js, js/services/autosleep.js
=> HOTFIX #457

locales/pt.json
Add Portuguese (Brazil) locale
=> Add pt-BR Locale

js/services/autosleep.js, main.js, motion.js
Fixing issues when motion is not defined in the config
=> manual changes from #479

sonus.js
sonus.js will now use the keyfile to load the project ID.
sonus.js will now check to make sure the model file exists and default to snowboy.umdl if it does not.
prepping for config.js by adding the capability of using config.general.language as well as config.language
=> remove projectId requirement in config.

app/js/controller.js, app/locales/en.json, index.html
*  removed "Screen On" & "Screen Off" voice commands
*  removed "Wake Up" voice command
*  "Sleep" voice command now calls AutoSleepService.sleep function
* Hotword now wakes the mirror by turning on screen if it is sleeping.
=> Patch Sleep Functionality

index.html, plugins/maker/config.schema.json, plugins/maker/controller.js, plugins/speech/service.js
A simple code-less way to add custom functionality to the mirror.
=> Adding maker channel (HomeAutomation, IFTTT, Custom HTTP Requests, etc)

plugins/calendar/service.js
=> [FIX] Return labels for recurring events

app/js/controller.js, config.default.json, index.html, main.js, plugins/autosleep/config.schema.json, plugins/autosleep/controller.js, plugins/autosleep/service.js, remote.js, remote/index.html, remote/remote-client.js
=> fix issue on TVs displaying no signal

plugins/search/config.schema.json, plugins/soundcloud/config.schema.json
missing titles caused issue with youtube and soundcloud... also why youtube likely wasn't working for many today... 
fixes #512
=> Hotfix for missing section configUI

app/js/controller.js, app/js/focus.js, index.html, plugins/dilbert/controller.js, plugins/giphy/controller.js, plugins/map/controller.js, plugins/reminder/controller.js, plugins/remote/controller.js, plugins/search/controller.js, plugins/soundcloud/controller.js, plugins/timer/controller.js, plugins/xkcd/controller.js
Use `$rootScope.$broadcast` to set our focus inside a service that is accessible from all plugin controllers.
Laying the groundwork to clean up autosleep in the controller.
Fixing #258 and #473.
=> use a service to track focus. fixes #258. fixes #473

app/js/controller.js
1 line fix for Locales!
- add related
- issues here
=> fixing #376 locales

plugins/greeting/controller.js
Now greetings should render on the mirror
#508
=> fix greetings on the mirror. fixes #508

remote/index.html, remote/style.css
connection bar was shifted in some browsers due to missing </div> for <div class="container">
No Issues
=> added missing </div>

package.json
Removed "npm" and "install" packages from dependencies in package.json. I highly suspect this is an accident (e.g. npm install --save npm install somepackage).
- add related
- issues here
=> removed "npm" and "install" packages from dependencies

scripts/conf-audio.sh
removes the comment line from exported file contents
- #495
=> fix for conf-audio.sh

remote/index.html, remote/index_nonIOS.html, remote/ios.html, remote/remote-client.js
=> Added ios text input

plugins/light/config.schema.json
=> Add missing brace.

main.js, plugins/autosleep/config.schema.json, plugins/speech/config.schema.json, sonus.js
- Using `path.resolve()` to 'resolve' issues with file names in the config.
- Fixing up the "first run" so people don't get scary errors
- Fixing bug where when the mirror wants to turn on the monitor it turns it off instead
=> Fixing path problems in the config

plugins/tvshows/controller.js
Will not longer show errors when no TV shows are added.
=> Fix browser console errors with null tv show lists.

main.js, scripts/pi-install.sh
- Check for the dev flag in all arguments
- Alias script to `npm run *`
- Fix final message on install script
=> Mirror CLI fixes

scripts/conf-audio.sh
added whiptail menus to Audio Config Script
enhancements to fixes already implemented
#540 
#495
=> added whiptail menus to Audio Config Script

sonus.js
Huge performance boost when using `arecord` over `rec`. Hooray!
=> perf boost for sonus using arecord

app/locales/fr.json, plugins/light/service.js
French translation and light service fix
Fix light service errors :
- index for the spokenWords tab must be 'w' and not 'i'
- in french, Google speech API give "100 %" and not "100%" ==> need to split the condition for the percentage value
=> French translation and fix on light service

config.default.json, plugins/fitbit/config.schema.json
test to fix fitbit values not existing due to previous values overriding defaults
- add related
- issues here
issues noted on discord chat
=> add defaults for fitbit to config.default.json

plugins/geolocation/config.schema.json, plugins/weather/config.schema.json, plugins/weather/controller.js, remote/config.schema.js
after latest merge in dev and conflict resolutions weather was missing from configUI. fixed that in config.schema.js
fixed issue with weather not displaying and syntax of jsonp() call
reformated links in geolocations and weather so that the link wasn't in section title.
=> fix config.schema.json for weather and other fixes

plugins/autosleep/service.js
energyStar functionality wasn't fully broken out as a separate task vs TV. I corrected that.
also had variable names consistent with other variable names using lowerCamelCase.
removed bleep and done from service object and created a var function definition.
n/a
=> Separate the energyStar Function from TV function.

main.js, remote/index.html
=> patch error with main.js not finding default.json

app/locales/ko.json
Korean Translation is NOT correct -> change&remove translation and add new translation
- change korean translate
- korean translate is not correct
=> change korean translate

plugins/autosleep/service.js
Fixes Issue #655
Hotfix
- #655
=> fix issue #655

app/css/main.css, app/locales/en.json, index.html, plugins/commitstrip/controller.js, plugins/commitstrip/index.html
Added a Commit Strip comic using RSS feed from: [http://www.commitstrip.com](http://www.commitstrip.com)
Wanted to try an easy plugin before I set myself the task of some more complex integrations.
None, new feature
- [Y ] I have read and understand the CONTRIBUTIONS.md file
- [Y ] I have searched for and linked related issues
- [ N/A] I have added config.schema.json file if config option are required.
- [Y ] I am NOT targeting master branch
=> Added CommitStrip comic

app/locales/pt.json
Corrected a few words and predicted possible words for commands that can be used.
No issue.
=> Portuguese language fixes

app/locales/de.json
added new translations, fixed existing (wrong translations or missing optionals)
=> updated german translations

README.md, package.json
=> Patch 1 (#731)

package.json
Electron 3.x to avoid incorrect glibc libs
electron/electron#16205
=> Electron 3.x to avoid incorrect glibc libs

main.js, sonus.js
=> revert sonus to as master.. no changes required.. still need main.js recovery

plugins/greeting/controller.js
hotfix delete accidental extra line
- add related
- issues here
- [ x] I have read and understand the CONTRIBUTIONS.md file
- [ x] I have searched for and linked related issues
- [ x] I have added config.schema.json file if config option are required.
- [x ] I am NOT targeting master branch
=> refix time of day greeting withut any messages

main.js
fix tab indention
- [ x] I have read and understand the CONTRIBUTIONS.md file
- [ x] I have searched for and linked related issues
- [ x] I have added config.schema.json file if config option are required.
- [ x] I am NOT targeting master branch
=> Sonus restart

.eslintignore, .gitignore, package.json, remote/config.html, remote/remote-client.js, scripts/copyjsonform
if the jsonform cdn libs become not available, the remote config crashes with a stacktrace.
add an error message
"Unable to load Required Libraries <br> Please try again in a few moments"
move the github repo locally an use the files directly
=>  add error handling if jsonform libs not available due to cdn problems

package.json, remote/remote-client.js
jsonform loading check fails on non jsonform page. 
add check for page name
#798
=> sdetweil patch config

package.json
jsonform loading check didn't account for config entry page
#798 
- [#] I have read and understand the CONTRIBUTIONS.md file
- [#] I have searched for and linked related issues
- [#] I have added config.schema.json file if config option are required.
- [] I am NOT targeting master branch
=> hotfix for config page v0.25

plugins/geolocation/service.js, plugins/map/controller.js, plugins/map/index.html
fixed fault when no geolocation info is provided in config.json
#817 
-
- [x ] I have read and understand the CONTRIBUTIONS.md file
- [x ] I have searched for and linked related issues
- [x ] I have added config.schema.json file if config option are required.
- [x ] I am NOT targeting master branch
=> Fix map and geolocation when no info configured

.travis.yml, main.js
fix startup config.json not found message
#674 
- issues here
- [x ] I have read and understand the CONTRIBUTIONS.md file
- [x ] I have searched for and linked related issues
- [x ] I have added config.schema.json file if config option are required.
- [x ] I am NOT targeting master branch
=> Fix startup config.json not found message

sonus.js
change sonus selection for recorder to use arecord on all arm* based systems
- add related
#801 
- issues here
=> fix wrong recorder selected on arm64 systems

app/locales/de.json, app/locales/en.json, app/locales/es.json, app/locales/fr.json, app/locales/it.json, app/locales/ko.json, app/locales/pt.json, plugins/weather/controller.js, plugins/weather/index.html
add line in weather forecast to show temp range for 'today'... text doesn't cover all the info
#707
=>  add today line to weather forecast, show temp range

plugins/weather/config.schema.json, plugins/weather/controller.js, plugins/weather/index.html, sonus.js
Darksky has dropped their free service, and is not providing any api keys at this time. 
- add related
- issues here
=> New weather provider replacing darksky

motion.js, motion.md, plugins/autosleep/config.schema.json, scripts/external_motion
Provide support for motion detection for external sources.. enable users to add support easily
(initial sample uses github motion project for webcam based detection)
=> add support for external motion detection

plugins/spotify/config.schema.json, remote/.config.default.json
defaults were wrong caused window to appear
=> Fix spotify defaults

main.js, scripts/external_motion
motion detection stopped after submit on config update
=> Fix motion background process on config recycle

package.json
=> change ver to 0.27

package.json, sonus.js
=> make Dev version number

main.js
pass parameter (usepm2) and if so, allow pm2 to manage restarts
https://www.digitalocean.com/community/tutorials/nodejs-pm2
#840
=> when Using pm2, do not self restart

app/js/loader.js
add lowercase and trim to allowe errors in user specified plugin name 
also for disabled plugins,  do not add css/controller or service entries to index.html
- #834 #839
=>  fix loader lowercase and trim user specified plugin name

plugins/spotify/service.js, remote/.config.default.json
change the defaults 
sendToDevice wrong field name for id used
#838 #837 
- issues here
=> Fix spotify2, enable defaults, fix transfer to command operation to match library

plugins/traffic/controller.js
=> Fix traffic, bad expression if no start time window set

scripts/external_motion
Motion reported cannot find sm process after remote config submit (was looking for npm)
- #847
=> Fix external motion command 

scripts/pi-install.sh
update script for  -y 
#849 
- issues here
=> npm upgrade prompts and fails, add -y

app/js/loader.js, app/locales/de.json, app/locales/en.json, app/locales/es.json, app/locales/fr.json, app/locales/it.json, app/locales/ko.json, app/locales/pt.json, plugins/commands/locales/de.json, plugins/commands/locales/en.json, plugins/commands/locales/es.json, plugins/commands/locales/fr.json, plugins/commands/locales/it.json, plugins/commands/locales/ko.json, plugins/commands/locales/pt.json, scripts/external_motion, scripts/pi-install.sh
redesign translation support, 
push modifiable text out to plugins
also enables translation of config panels, by plugin
enables plugin developer  control of plugin translation, without modifying core files. 
enable turn off plugin, remove commands from what can i say, and remote config
adds language support for the what can I say list next/prev
- #650 #738
=> New nls, separate language to plugins, construct on start, translate config ui.

app/js/loader.js, app/locales/es.json, app/locales/fr.json, plugins/commands/locales/de.json, plugins/commands/locales/it.json
copy/paste error on the base locale files -> plugins/commands/locales
=> fix copy paste error

plugins/search/index.html
change html to create iframe only when video focus, gets created each time
#473
=> fix for youtube only play once

app/locales/de.json, app/locales/en.json, app/locales/es.json, app/locales/fr.json, app/locales/it.json, app/locales/ko.json, app/locales/pt.json, plugins/reminder/controller.js, plugins/reminder/index.html
change logic and add html heading to make logic more simple
#647
=> fix reminder failure on duplicate reminder and processing

.gitignore, app/css/main.css
in portrait mode, the old fixed width for 1920 screen doesn't work.. new view width css fixes this
but breaks weather
#808
=> fix weather css to fixed pixels vs vw, breaks layout on portrait mode

.editorconfig, .gitignore, scripts/fixpm2.sh, scripts/pi-install.sh, scripts/pm2_smart-mirror.json
=> fix permissions on sandbox files, add missing install files

plugins/spotify/openauth.sh, plugins/spotify/service.js
enable easy authorization when user is on different system from sm 
#862
=> enable easy authorization when user is on different system from sm 

app/js/controller.js, app/js/logger.js, logging_index.html, plugins/light/controller.js, plugins/light/index.html
with new plugin loader, need to have plugins controllable
with the commands loaded in controller, we had stuff that worked, even tho it wasn't supposed to
#863
=> Move light plugin startup out of app/js/controller.js

app/locales/fr.json, plugins/autosleep/locales/fr.json, plugins/calendar/locales/fr.json, plugins/dilbert/locales/fr.json, plugins/fitbit/locales/fr.json, plugins/light/locales/fr.json, plugins/pluginconfig/locales/fr.json, plugins/timer/locales/fr.json, plugins/traffic/locales/fr.json
=> Fr translation correct [for @sdetweil]

package.json
=> fix angular sanitize version to specific level to match our angular version

scripts/pi-install.sh
remove '|| exit' from commands so we can log what happened
=> fix install  terminating early

package.json
=> update version 0.28

package.json
=> make develop version

plugins/weather/controller.js
fix weather provider climacell to  to use new V4 api 
#895
=> weather provider climacell changed their api to V4, all api keys no longer work. 

plugins/spotify/service.js
spotify doesn't play if idle
#900
spotify api returns 'NO_ACTIVE_DEVICE' when idle, need to specify device to play on in addition to the music tracks
- [X ] I have read and understand the CONTRIBUTIONS.md file
- [X ] I have searched for and linked related issues
- [X ] I have added config.schema.json file if config option are required.
- [X ] I am NOT targeting master branch
=> Fix spotify play after idle, defaults to default device

remote/config.schema.js
fix config builder loop hang on mac
=>  fix config hang on mac

package.json
=> move version number

plugins/search/controller.js
youtube controller  was changed, but the function using the data wasn;'t changed to match the search 
#910
=> fix coding using the youtube search results

plugins/speech/service.js
new speech service for sharing the mic had parm which was unclear on its use.
=> change recorder parm name to reflect its real purpose

plugins/fitbit/config.schema.json
the translation link have the wrong term
=>  fix typo in fitbit schema for auth link

plugins/weather/controller.js, scripts/installcblas
libatltas3)
- add related
- issues here
fix missing icons in weather
fix cblas pre-install for newer version (v3)
- fixes 
#915
=> fix missing icons in weather and fix cblas install for newer version 

remote/config.schema.js
arecord returns list text in locale dependent text
#916
=> mic not listed when system running non-english 

plugins/weather/controller.js, scripts/external_motion, scripts/pi-install.sh
fix install
external_motion
weeather
#931 
#932
#933
=> fix misc defects

plugins/todoist/service.js, plugins/weather/controller.js
=> Fix todoist
